### ISSUE TITLE
Simplify importing classes/functions

### ISSUE THREAD

**Issue by LiamPattinson** [jatkinson1000/archeryutils#3]
I think it'd be a good idea to expose some classes/functions to the top-level namespace. It'd be nice if we could do stuff like:

```python
import archeryutils as au
my_target = au.Target(...)
```
We'll have to be fairly selective though, as most of the internals probably don't need to be part of the user API.

**Comment by jatkinson1000** [comment]
Yep, probably easiest to arrange a meeting to discuss this at a convenient point?

**Comment by jatkinson1000** [comment]
@LiamPattinson I have implemented this over in #55 if you want to take a look and share any thoughts/review.
