### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by TomHall2020** [jatkinson1000/archeryutils#49]
Is there much else that needs to be done before this can be uploaded? 

Am currently working on a project using this and being able to properly install and version it rather than installing from source would be quite helpful. 

Happy to try and contribute if anything needs doing to prepare for this.

**Comment by jatkinson1000** [comment]
I could probably look at doing this in its current state with a bit of tidying to be honest (done is better than perfect etc.etc.)
I was hoping to improve the field handicaps, but have been too busy to do much recently so this may become something for a later version (and it's all unofficial at the moment anyway).

Always keen to see how it's useful.
How is your project packaged at the moment, as there are ways to add git repos to dependencies and point to specific commits/hashes? This could work in the interim. See [here](https://github.com/jatkinson1000/archerycalculator/blob/main/pyproject.toml) for an example.

**Comment by jatkinson1000** [comment]
@TomHall2020 Having refreshed my memory I think I'd like to close #2, #4, and #27 for release, as implementing these in future would likely be breaking changes, so best to set now.

#3 and #15 would be nice, but I think can be resolved in a backwards compatible way in future.

If you fancy taking a crack at #27 please do! - I have set out a rough plan for what would need doing in the issue.
Happy to help with guidance on forks/pull requests etc. if required.
I'll try and look at #4 and #2 this weekend depending on how much I freeze at a frostbite/EFAA course.

**Comment by TomHall2020** [comment]
Yeah, #27 looks pretty straightforward I can cook something up for that. 
The project isn't packaged as such, its a django web app so archeryutils is just a dependancy on the server side. At the moment the person I'm working on it with has just included this project as a submodule but the git pointer in requirements.txt would probably work better for us for now.

**Comment by TomHall2020** [comment]
Hate to add to the list but theres probably one more issue to go before release, #74

**Comment by jatkinson1000** [comment]
Yeah, it's been a bugbear of mine for a while, I'll do it after #2 as it should hopefully be relatively straightforward with some default arguments.

**Comment by jatkinson1000** [comment]
Revisiting this, and once we close #57 (PR ready), #71 (PR #82 WIP), and #56 (PR #59 close) I think we are good to go.

**Comment by jatkinson1000** [comment]
#57 is now closed, #56 is now closed, #71 is only one remaining.

PR for PyPI release has been opened in #87
