### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jatkinson1000** [jatkinson1000/archeryutils#50]
Aiming for a release in #49 we should add some documentation.

Sphinx may be a good option

**Comment by LiamPattinson** [comment]
I've added Sphinx to a bunch of projects, and it looks like your docstrings are already very close to NumPy style (only spotted a few things that might not be parsed properly). I could have a go if I find time in the next few days, but don't let that stop you if you'd rather get things done sooner.

One thing I haven't set up before is readthedocs integration, which would publish new versions of the docs whenever the code is updated. I'm sure I could figure it out though.
