### ISSUE TITLE
Make some handicap_functions methods private

### ISSUE THREAD

**Issue by jatkinson1000** [jatkinson1000/archeryutils#60]
All except `handicap_from_score` and `﻿﻿print_handicap_table` should be private.
To do this requires removing the explicit tests for any private functions and instead testing them implicitly through the above two.

This will require tests writing for `print_handicap_table` which should bump coverage up.

**Comment by TomHall2020** [comment]
I wonder, doe's it make logical sense to remove the explicit tests? It seems unit testing is a perfectly valid reason to break the private convention and use those functions directly.

**Comment by jatkinson1000** [comment]
This is likely to be addressed in the upcoming PR dealing with #2 
At least, it gives a significant shake up to everything and is likely to render much of this moot, I think.
