### ISSUE TITLE
Feature Request: Add 11-zone (Lancaster) Target to scoring systems

### ISSUE THREAD

**Issue by jatkinson1000** [jatkinson1000/archeryutils#69]
It would be good to add the Lancaster Archery target as a possible scoring system (X is 11, compound and full face), and the Lancaster Classic round (18m, 40cm).

See chapter 4 of the [Lancaster Classic Rules](https://www.lancasterarcheryclassic.com/rules).

e.g.
```python
import archeryutils as au

myLancastertarget = au.Target("Lancaster", 40, 80)
myLancasterpass = au.Pass(30, "Lancaster", 40, 80, indoor=True)
myLancasterClassicRound = au.Round("lancaster_classic", [myLancasterpass, myLancasterpass])

myLancastertarget_comp = au.Target("Lancaster_6_ring", 40, 80)
myLancasterpass_comp = au.Pass(30, "Lancaster_6_ring", 40, 80, indoor=True)
myLancasterClassicRound_comp = au.Round("lancaster_classic_compound", [myLancasterpass_comp, myLancasterpass_comp])
```

**Comment by TomHall2020** [comment]
Agree, though I think "11_zone" is a better name. "lancaster_compound" is confusing as in the existing systems "10_zone_compound" refers to scoring 10,9,9 inside the gold (as opposed to 10,10,9), but to my understanding all bowstyles at lancaster just score 11,10,9. Do you mean "lancaster_6_ring" for the compounds?

**Comment by jatkinson1000** [comment]
Yes, that probably makes more sense.
Trying to think how people usually refer to it - "Lancaster Scoring", "X is 11" - I think 11-zone makes sense.

And yes, I do mean 6_ring!
