### ISSUE TITLE
Feature Request: Define Pass using existing Target

### ISSUE THREAD

**Issue by jatkinson1000** [jatkinson1000/archeryutils#70]
Often we define a target before defining a Pass, especially in the examples.
However, we then pass exactly the same information to the `Pass` constructor that internally re-makes a `Target`.
It would be nice, if we have already constructed a `Target`, to pass this directly to an alternative `Pass` constructor.

May need to be careful with ensuring that we use a copy rather than a reference in the `Pass`...

```python
import archeryutils as au

mytarget = au.Target("10_zone", (122, "cm"), (70.0, "m"))

mypass = au.Pass(36, mytarget)
```

**Comment by TomHall2020** [comment]
I had been looking at this as part of #59 already as I needed to initalise Passes from an already constructed Target object there. 
But I agree that it makes sense in general, and possibly should even be the default, as my thought process when working the REPL usually goes something like:
```python
# make a target
>>> t = Target("10_zone", (122, "cm"), (70.0, "m"))

# try and make a pass with it
>>> p = Pass(36, t)
ValueError(...)

# swear, remember I have to recreate the Pass with the same parameters
>>> p = Pass(36, "10_zone", (122, "cm"), (70.0, "m"))
```

**Comment by jatkinson1000** [comment]
OK, My gut suggests doing it as a separate PR, but happy for it to come from #59 given you have already started.
I think having target as default, and then having a `pass_from_base_target_data` classmethod (not called that, but I can't come up with a more concise but clear name right now) is probably best, as you suggest.

Other option would be overloading, but I think that could get messy given they are mutually exclusive argument options rather than one being a subset.

**Comment by TomHall2020** [comment]
Got an implementation using `at_target` for the classmethod name, obviously that one open to change but it seems not too bad. Snuck in some useful reprs because trying to check these in the repl without them was deeply unpleasant.

Mini PR incoming.
